version: '{build}-{branch}'

clone_folder: C:\git\LuaConsole
skip_tags: true
max_jobs: 2

image: Visual Studio 2019
platform: x64
branches:
  only:
  - master


build_script:

- cmd: >-
    prereqs.bat download
    
    build.msvs.bat driver luajit
    
    build.msvs.bat package lua-5.3.5
    

test: off
deploy: off

on_success:
- cmd: echo Build successful!

on_failure:
- cmd: echo Build failed!

on_finish:
- cmd: echo Building finished.

