language: c

cache:
  directories:
    - $HOME/cistore

dist: trusty
sudo: true

compiler:
  - gcc

braches:
  only:
    - master

script:
  - bash travis_test.sh

after_success:
  - echo "Build and tests successful"

after_failure:
  - echo "Build and tests failed."

