language: c

cache:
  directories:
    - $HOME/cistore

dist: trusty
sudo: true

compiler:
  - gcc

braches:
  only:
    - master

build_cmd: &build_cmd
  - ./travis.sh

before_script:
  - chmod +x travis.sh
  - chmod +x build.sh
  - chmod +x prereqs.sh

jobs:
  include:
    - stage: build
      script: *build_cmd
      os: linux
    - stage: build
      script: *build_cmd
      os: osx

after_success:
  - echo "Build and tests successful"

after_failure:
  - echo "Build and tests failed."

