language: c

cache:
  directories:
    - $HOME/cistore

dist: trusty
sudo: true

compiler:
  - gcc

braches:
  only:
    - master



before_script:
  - chmod +x travis.linux.sh
  - chmod +x travis.mac.sh
  - chmod +x build.linux.sh
  - chmod +x build.mac.sh
  - chmod +x prereqs.sh



build_cmd_linux: &build_cmd_linux
  - ./travis.linux.sh

build_cmd_mac: &build_cmd_mac
  - ./travis.mac.sh

jobs:
  include:
    - stage: build
      script: *build_cmd_linux
      os: linux
    - stage: build
      script: *build_cmd_mac
      osx_image: xcode10.2
      os: osx



after_success:
  - echo "Build and tests successful"

after_failure:
  - echo "Build and tests failed."

