language: c

dist: trusty
sudo: true

compiler:
  - gcc

braches:
  only:
    - master

cache:
  directories:
    - $HOME/luajit-2.0

script:
  - bash travis_dependencies.sh
  - bash build.sh

after_success:
  - echo "Build successful. Testing."
  - bash travis_test.sh
after_failure:
  - echo "Build failed."

