name: Linux LuaConsole CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ./prereqs.sh download
      run: ./prereqs.sh download
    - name: ./build.linux.sh driver luajit
      run: ./build.linux.sh driver luajit
    - name: ./build.linux.sh package lua-5.4.2
      run: ./build.linux.sh package lua-5.4.2

