name: Linux LuaConsole CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ./prereqs.sh download
      run: ./prereqs.sh download
    - name: ./build.linux.sh driver luajit
      run: ./build.linux.sh driver luajit
    - name: ./build.linux.sh package lua-5.4.2
      run: ./build.linux.sh package lua-5.4.2
  build_mingw:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: prereqs.bat download
      run: prereqs.bat download
    - name: build.mingw.bat driver luajit
      run: build.mingw.bat driver luajit
    - name: build.mingw.bat package lua-5.4.2
      run: build.mingw.bat package lua-5.4.2

